version: '2'
services:
    elasticsearch:
        image: elasticsearch:6.5.0
        volumes:
            - ./esdata:/usr/share/elasticsearch/data
    kibana:
        image: kibana:6.5.0
        links:
            - elasticsearch
    screeps-stats:
        build: .
        links:
            - elasticsearch:elasticsearch
        entrypoint: wait-for-it/wait-for-it.sh -t 30 elasticsearch:9200 -- python /screeps-stats/screepsstats.py
    nginx:
        image: nginx:1.9.6
        ports:
            - "5601:80"
        links:
            - kibana
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/htpasswd:/etc/nginx/htpasswd:ro
